services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

 #   ldap.logger:
 #       class: Refulgent\ContaoLDAPSupportBundle\Service\Logr
 #       public: true
 #       arguments:
 #           - '@logger'


    # makes classes in src/AppBundle available to be used as services
 #   Refulgent\ContaoLDAPSupportBundle\Service\:
 #       resource: '../../Service/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        # exclude: '../../src/AppBundle/{Entity,Repository}'
