services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

 #   ldap.logger:
 #       class: Refulgent\ContaoLDAPSupportBundle\Service\Logr
 #       public: true
 #       arguments:
 #           - '@logger'


    # makes classes in src/AppBundle available to be used as services
 #   Refulgent\ContaoLDAPSupportBundle\Service\:
 #       resource: '../../Service/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        # exclude: '../../src/AppBundle/{Entity,Repository}'


 #    HeimrichHannot\Ldap\Logr\:
 #        resource: "/var/www/de.grateful-death/system/modules/ldap/classes/Logr.php"

 #    HeimrichHannot\Ldap\Logr:
 #        arguments: ['@logger']
 #        tags:
 #            - { name: monolog.logger, channel: ldap }

 #    monolog.logger:
 #        class: HeimrichHannot\Ldap\Logr
 #        arguments:
 #            - "@logger"

 #   HeimrichHannot\Ldap\Logr:
 #       arguments:
 #           $logger: '@monolog.logger'
 
 #   ldap.logger:
 #       public: true;
 #       arguments:
 #           $logger: '@monolog.logger'
 
 #   ldap.logger:
 #       class: Refulgent\ContaoLDAPSupport\LdapPersonGroup
 #       public: true
 #       arguments:
 #           - "@logger"
            
 #   ldap.logger:
 #       class: HeimrichHannot\Ldap\Logr
 #       public: true
 #       arguments:
 #           $logger: '@monolog.logger'
 
 #   ldap.logger:
 #       class: HeimrichHannot\Ldap\Logr
 #       public: true
 #       calls:
 #           - [setLogger, ['@logger']]
 
 #   ldap.logger:
 #       public: true
 #       factory:   ['@HeimrichHannot\Ldap\LogrFactory', createLogr]
 #       arguments: ['@logger']

 #   ldap.logger:
 #       alias: 'monolog.logger'
 #       public: true

